### PR TITLE
Added support for null safety

### PR DESCRIPTION
**Pull request by andzejsw**
Added support for Flutter 2.0 and Null safety logic.

### CODE REVIEW

**Comment by andzejsw** [comment]
@builttoroam can you take a look?

**Comment by andzejsw** [comment]
@nickrandolph do you know who is maintainer of this package? I just see that you are last one, whos commit were implemented

**Comment by nickrandolph** [comment]
@andzejsw would you be interested in being a maintainer?

**Comment by andzejsw** [comment]
> @andzejsw would you be interested in being a maintainer?

Sure. I am interested in that!

**Pull request closed without merging**
