### PR TITLE
Cherry pick request FullAccess on iOS17+ (#497)

### PR DESCRIPTION
**Pull request by LeonardoCaracho**
Cherry-pick referencing this [issue](https://github.com/builttoroam/device_calendar/pull/497).

### CODE REVIEW

**Review by LuizFritsch — APPROVED** [review]

**Comment by LuizFritsch** [comment]
Hello, I'm looking forward to having this PR merged and the plugin working :)
Do you know by any chance when you will be able to review this PR @thomassth?

**Comment by istornz** [comment]
Any news about merging this mandatory fix for iOS 17+?
Thanks :)

**Comment by IVLIVS-III** [comment]
@LeonardoCaracho thanks for creating this PR. Sorry for not looking at this sooner.
Please also change the version in `pubspec.yaml` and add a new entry in the `CHANGELOG.md`.
Then I can merge this PR to get the fix published. Without the version change, we cannot publish to pub.dev.

**Comment by LeonardoCaracho** [comment]
> @LeonardoCaracho thanks for creating this PR. Sorry for not looking at this sooner. Please also change the version in `pubspec.yaml` and add a new entry in the `CHANGELOG.md`. Then I can merge this PR to get the fix published. Without the version change, we cannot publish to pub.dev.

**Comment by LeonardoCaracho** [comment]
> @LeonardoCaracho thanks for creating this PR. Sorry for not looking at this sooner. Please also change the version in `pubspec.yaml` and add a new entry in the `CHANGELOG.md`. Then I can merge this PR to get the fix published. Without the version change, we cannot publish to pub.dev.

Done! thanks for the reply ;)

**Review by IVLIVS-III — DISMISSED** [review]

**Comment by istornz** [comment]
@LeonardoCaracho I think you will need to change file `device_calendar/example/lib/presentation/pages/calendar_event.dart` line 867.

Change with:

```
style: ElevatedButton.styleFrom(
  foregroundColor: Colors.white,
  backgroundColor: Colors.red),
)
```

**Review by istornz — APPROVED** [review]

**Review by IVLIVS-III — APPROVED** [review]

**Comment by IVLIVS-III** [comment]
Bildschirmfoto 2024-02-28 um 17 51 09

I'm afraid, my write access is not sufficient to merge this PR… the `master` branch has some extra protection.
We will need @thomassth to do the merge.

**Comment by thomassth** [comment]
Release pipeline doesn't work (again)

While I got the permission to renew the pub key, GitHub cred access is still locked from me

Paging @nickrandolph

**Comment by istornz** [comment]
Thanks guys for your speed!

**Comment by fourthperson** [comment]
Hello guys, @thomassth and @IVLIVS-III , you forgot to add the new recommended `namespace` value in the android block so as to support Gradle 8.0 and consequently, newer android versions.

https://developer.android.com/build/configure-app-module#set-namespace

it is supposed to go into the 
`android {
>namespace: 'your-namespace-here'
}` block  of your `modeule/build.gradle` file.

**Pull request merged**
