### PR TITLE
Timezone changes

### PR DESCRIPTION
**Pull request by andzejsw**
PR contains merged timezone logic fixes + new changelog updates.

### CODE REVIEW

**Comment by andzejsw** [comment]
@nickrandolph I think this PR can be release. Version is set to 4.0.1. 
When we will do  4.x Release not Prerelease?

**Comment by nickrandolph** [comment]
@andzejsw can I get you to just PR the changes to builttoroam:develop - I've changed the base branch in this PR but I think you need to rebase your branch again.
My suggestion going forward is that you create new local branches based on builttoroam:develop - this will avoid having to rebase when you PR changes

**Comment by andzejsw** [comment]
@nickrandolph ```
andzejsw@DESKTOP-7EL3H10:/mnt/c/app/device_calendar$ git rebase fork/develop 
Current branch develop is up to date.
```
For me looks like, that there is no rebase needed

**Comment by thomassth** [comment]
This is bacause during merge rebase, ALL previous commits are set with a different commit ID.

See [here](https://github.com/andzejsw/device_calendar/commits/develop) and [here](https://github.com/builttoroam/device_calendar/commits/develop) and notice how the commit IDs of the same commit differs.

Since we can't fix upstream, we can make git recognize and replace the downstream edits. See [here](https://github.com/builttoroam/device_calendar/pull/302#issue-638371760) for my attempt.

I'm trying to do the separate branch thing at #304 . If it solves the issue I'll write a contribute md.

**Comment by nickrandolph** [comment]
tbh I think it's easier to take a fresh branch and cherry pick the changelog commit

**Comment by nickrandolph** [comment]
The only change in this PR is the update to the change log, Which has been pushed in #306

**Pull request closed without merging**
