### PR TITLE
Request FullAccess on iOS17+

### PR DESCRIPTION
**Pull request by junqi**
Issue #490 

A distinction between write-only access and full access has been made since iOS17.
https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels

This PR obtains full access, but it may be inappropriate if you intend to be able to handle write-only access separately.

### CODE REVIEW

**Comment by thomassth** [comment]
The pipeline might need some updates too it seems

**Comment by junqi** [comment]
I have fixed the build test based on the error message.
(Please note that the minSdkVersion of Android has been increased.)

**Comment by thomassth** [comment]
lgtm

**Review by thomassth — APPROVED** [review]

**Comment by Anjali-Rightpoint** [comment]
@thomassth When will this PR changes be released, or by when will the next version of device_calendar plugin will release with iOS17 updates?

**Comment by thomassth** [comment]
Someone cherrypick the commit and start a PR to the release branch (`master`)

I'll approve that

**Comment by LeonardoCaracho** [comment]
> Someone cherrypick the commit and start a PR to the release branch (`master`)
> 
> I'll approve that

Hi @thomassth, I just started a cherry-pick PR to master as you suggested.

**Comment by juanpabloCamus** [comment]
Hi, when this is supposed to be released? Thanks

**Pull request merged**
