### PR TITLE
Timezone implementation

### PR DESCRIPTION
**Pull request by andzejsw**
Android implementation should now work with Timezone logic. So should example build. 
Currently haven't looked on iOS.

### CODE REVIEW

**Comment by nickrandolph** [comment]
@andzejsw did you want to fix up the ios build before we merge this PR in? Or did you want to create separate item to track the iOS work? My concern with merging this in without the iOS piece is that the code in develop would currently in an unusable state for iOS.

**Comment by andzejsw** [comment]
@nickrandolph I would like to take a look on iOS soon. Hopefully will fix iOS part in this PR.  I will let you know what is my progress.
Also feel free to test Android part.

**Comment by andzejsw** [comment]
@nickrandolph tested on iOS. Logic works also there. There was some errors in example app not related to this issue which I also fixed. In my opinion we can merge this PR to dev branch. But you and @thomassth also can test if you want before merging. 
As far as I se, there is multiple issues regarding this PR, so I guess we need to publish this as soon as we can.

**Comment by andzejsw** [comment]
Should I increase version!?

**Comment by andzejsw** [comment]
@thomassth, @nickrandolph Can anyone of you take a look on this PR? And changes I made?

**Comment by nickrandolph** [comment]
Yep give the version a small increment (third digit is fine). I will try to review the changes in next couple of days

**Comment by andzejsw** [comment]
Thanks. Did it.

**Review by nickrandolph — APPROVED** [review]

**Comment by nickrandolph** [comment]
@andzejsw can you rebase your branch please - I've reviewed these changes but when I got to merge I'm getting an error stating that "This branch cannot be rebased due to conflicts"

**Comment by andzejsw** [comment]
It should be ok now. I did git rebase.

**Comment by andzejsw** [comment]
Latest commit fixes issue #https://github.com/builttoroam/device_calendar/issues/241

**Review by nickrandolph — APPROVED** [review]

**Comment by nickrandolph** [comment]
@andzejsw I'm still seeing rebase issues due to conflicts. Did you rebase off develop or master?

**Comment by thomassth** [comment]
I have 

> @andzejsw I'm still seeing rebase issues due to conflicts. Did you rebase off develop or master? Also, make sure you rebase off the remote builttoroam:develop branch, rather than the local develop on your fork (unless you've updated your develop)

I have a hard time merging upstreams, because somehow all commits from #287 has different commit ids then my own. If I force merge them there will be duplicated items on the git tree.
I'm not very familiar with git, is there a best practice in these situations?

**Comment by nickrandolph** [comment]
Yes, we do a "rebase and merge" when merging in changes to develop - this leaves a cleaner commit history.
If you fetch builttoroam:develop and then rebase your local branch onto it, you should be good to go.

**Comment by andzejsw** [comment]
I will take a look to rebase with builttoroam:develop, but yeah, it looks like a lot of extra work. Will see how much time it takes.

**Comment by andzejsw** [comment]
@nickrandolph rebasing done.

**Comment by nickrandolph** [comment]
@andzejsw did you force push after rebasing? you need to force push otherwise you end up with duplicates in the commit history - if you notice there's twice as many commits in the history than there were previously

**Comment by nickrandolph** [comment]
Yep you'd need to do the rebate again but this time doing a force push. Sorry to be such a pain about this but it helps to keep the commit history clean.

**Comment by andzejsw** [comment]
@nickrandolph Everything rebased and looks like, that now everything works as it should

**Review by nickrandolph — APPROVED** [review]

**Comment by nickrandolph** [comment]
@andzejsw a big thank you for all the time and effort put into getting this PR across the line!

**Comment by andzejsw** [comment]
@nickrandolph, @thomassth I think that these changes should be published to pub.dev as Prerelease or even new release. What do you think?

**Comment by nickrandolph** [comment]
@andzejsw do you mind pushing a quick PR with updated version number and updates to readme (if required). I'll merge the PR and then do a PR to release to push a new prerelease version

**Pull request merged**
