### PR TITLE
Pull request related to [Issue 298 - Change of actual Recurrence Rule Class]

### PR DESCRIPTION
**Pull request by GoldenSoju**
Pull request related to [Issue 298 - Change of actual Recurrence Rule Class](https://github.com/builttoroam/device_calendar/issues/298)

### CODE REVIEW

**Comment by thomassth** [comment]
It seems strange to have this many lines changed

Maybe try a fast forward merge?

**Comment by GoldenSoju** [comment]
@thomassth 
Sorry, but regarding fast forward merge, would you mind telling me how to do it the best way? [This SO question](https://stackoverflow.com/a/63888023/13558952) doesn't really clarify it for me.

**Comment by thomassth** [comment]
There's no button on github that does that unfortunately

In my workflow (VSCode), I use Git Graph:
1. add the main repo in a separate branch (there's a setting in Git graph, or you can do that with command line)
2. pick "merge to current branch" at the latest commit
3. uncheck the first option so that it will do a fastforward merge

Or you can just `git push` cause it does fastforward by default.

**Comment by thomassth** [comment]
Also, may I ask what was changed in your `rrule`? If it's ready, you should submit a PR over there too. Or else we may need to put it into our package somehow.

**Comment by GoldenSoju** [comment]
@thomassth 

1. Please check the new pull request [403](https://github.com/builttoroam/device_calendar/pull/403).
2. Most notable changes to Rrule were:

- adding toJson/fromJson functions
- some utility functions (like: Frequency to Int / Int to Frequency)
- some changes that you also commited (removed deprecated/not needed packages etc.)
- renamed Frequency to RecurrenceFrequency 

Please see also [this change report](https://github.com/GoldenSoju/rrule/commit/6325f7eecd45739132317cbfe73ddc1fd59e2820).

**Comment by thomassth** [comment]
Closing this since we have #403 now.

**Pull request closed without merging**
