### PR TITLE
Using Github Actions

### PR DESCRIPTION
**Pull request by thomassth**
I'm trying to rewrite the current CI/CD using Github Actions

So far CI is simple enough

Things to work on:

- [x] flutter publish test
- [x] generate changelog summary from `CHANGELOG.md`
- [x] add releases to Github

### CODE REVIEW

**Comment by thomassth** [comment]
Seeing other examples, most are recommending utilizing Github's own secret store, and access it during CI/CD

Maybe we should do that as well

**Comment by MooNag** [comment]
I like this. Looks really easy to maintain too. This plugin really needs a better release workflow given how infrequent they are.

**Comment by thomassth** [comment]
All functions should be ready

Some organizing are probably needed; and we may need to test publish on prod because we don't have the cred keys to test

**Comment by thomassth** [comment]
Might want to do a squash merge this time due to all the commits.

**Review by sowens-csd — COMMENTED** [review]
Are the branches right in prerelease.yml? It says _Development Release_ but then references `release, hotfix`, should that be `develop`? Just trying to make sure I understand the goal of the two Actions. 

Looks like both prerelease and release are set to dry run, not actually publish, right now so they look safe in any event. If that's right then I should approve and we can test. Confirm?

**Comment by thomassth** [comment]
Dry run first just to be sure I think

The branch names and actions came from the original pipeline. not sure why there's that many divisions tho

**Review by sowens-csd — APPROVED** [review]
This seems good for testing the dry-run. There's some documentation and other changes but I can contribute after this is merged.

**Pull request merged**
