### PR TITLE
[WIP] fix createCalendar on iOS device when iCloud is open

### PR DESCRIPTION
**Pull request by thiszhong**
#223 
This resolved my problem. But I am not a iOS developer, So have a check, please.

### CODE REVIEW

**Comment by nickrandolph** [comment]
@thiszhong can you confirm that the iCloud calendar always has the title "iCloud" (perhaps links to any docs). 
Am I correct in saying that when user has iCloud enabled, they don't see any local source types?

**Comment by thiszhong** [comment]
> @thiszhong can you confirm that the iCloud calendar always has the title "iCloud" (perhaps links to any docs).
> Am I correct in saying that when user has iCloud enabled, they don't see any local source types?

Actually I'm not sure because I don't know much about ios. But it's the best answer I can find.
[https://stackoverflow.com/a/15980556](https://stackoverflow.com/a/15980556) 

[https://github.com/TheAlmightyBob/Calendars/issues/22#issuecomment-236888276](https://github.com/TheAlmightyBob/Calendars/issues/22#issuecomment-236888276) 

[https://oleb.net/blog/2012/05/creating-and-deleting-calendars-in-ios/](https://oleb.net/blog/2012/05/creating-and-deleting-calendars-in-ios/) 

> Update February 12, 2014 and March 05, 2014: Robert de Jong pointed out to me that the source title is indeed user-editable (Settings > iCloud > Account > Description), which makes this way of detecting the iCloud calendar store unreliable. Robert suggests this approach:

`EKSource *theSource = [[eventStore defaultCalendarForNewEvents] source];`

> For most users, this should provide the iCloud source, if it’s set up, or the local source, if not. But it might as well return a totally different source if the user has configured another default. There seems to be no 100% reliable way to retrieve the iCloud source with public API.  

[Apple Watch for Developers - p44](https://books.google.com/books?id=RL9OCgAAQBAJ&pg=PA44&lpg=PA44&dq=ios+calendar+sourceType.title+icloud&source=bl&ots=FC5NlKRLYT&sig=ACfU3U2tqZK0D1ucKNO2TPGbpJQ3wdLTQg&hl=zh-CN&sa=X&ved=2ahUKEwj5-KWemfHpAhVHtZ4KHZhbB4QQ6AEwAXoECAoQAQ#v=onepage&q=icloud&f=false)



Feel free to close it if there is a better answer.

emm... I think it is a check when local source is nil.

**Comment by nickrandolph** [comment]
@thiszhong I think this should be a fall back process - look for .local source type. If that doesn't exist, then use
EKSource *theSource = [[eventStore defaultCalendarForNewEvents] source];
to find the appropriate source.
I'm not convinced that using the source of the defaultCalendarForNewEvents is always the correct behaviour. Hence using it only as a fallback. 
Thoughts?

**Comment by petekblaz** [comment]
Any info on when this will be merged?

**Comment by nickrandolph** [comment]
@petekblaz see my comment above - I think changes are required before we can merge this.

**Comment by hnvn** [comment]
Why don't use `eventStore.defaultCalendarForNewEvents` ?

**Comment by hnvn** [comment]
Why don't use `eventStore.defaultCalendarForNewEvents.source`. I would like to handle it like:
```swift
guard let defaultSource = eventStore.defaultCalendarForNewEvents?.source else {
   result(FlutterError(code: self.genericError, message: "Default calendar was not found.", details: nil))
   return
}
                
calendar.source = defaultSource;
                
try eventStore.saveCalendar(calendar, commit: true)
result(calendar.calendarIdentifier)

```

**Comment by rjgpereira** [comment]
Hi guys! 

I think it would be useful to give a chance to pick the calendar source. So, my suggestion is creating a methodCall to retrieve the source and pass it to the "createCalendar". Otherwise, you would default to the defaultCalendarForNewEvents like @hnvn is suggesting.

What do you think?

**Comment by thiszhong** [comment]
A new approach seems to be needed.

**Comment by elaishane** [comment]
Hey guys is this issue fixed/not. My clients are asking for a solution. Somebody please give a solution asap

**Comment by michaelchiowong** [comment]
hi, guys, any updates for this ?

**Comment by sj1914** [comment]
Would love a solution to this, i think the fallback option sounds like a good alternative to the current behaviour!

At the moment the only option, would love to know if someone has thought of an alternative or workaround, seems to be to provide some troubleshooting to users to tell them to turn off icloud while we sync their calendar for the first time, which doesn't seem ideal.

I want to keep events created by my app separate as it makes syncing and unsyncing more manageable. Without the ability to create a new calendar on iOS I'm super stuck. Help!

**Pull request closed without merging**
