### PR TITLE
gradle fix

### LINKED ISSUE #496: The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':device_calendar' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

Run a `flutter doctor` so we can rule out env issues

[✓] Flutter (Channel stable, 3.10.6, on macOS 14.0 23A5301h darwin-arm64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.80.2)
[✓] Connected device (4 available)
[✓] Network resources

### PR DESCRIPTION
**Pull request by thomassth**
Trying to fix #496 #483 and others

### CODE REVIEW

**Review by IVLIVS-III — APPROVED** [review]
LGTM

**Comment by bardram** [comment]
Perfect. Now we just need to publish it to pub.dev...

**Comment by Finni123** [comment]
@bardram I'm waiting for this too. Can we do anything to speed it up?

**Comment by laminr** [comment]
Hi Folks,
Do you have turn around regarding this issue, my project is blocked because of that.
Is it the only library to get calendar entries?

**Comment by thomassth** [comment]
I've checked the pipeline last night, key's still expired

I had a chat with @nickrandolph some weeks ago, but there's no update since then

Meanwhile you can use the git branch directly in your pubspec instead, the master branch is basically what the release will (should) be

**Comment by nickrandolph** [comment]
Apologies all. Been sidetracked on getting other releases out. Will try to get API key asap and organise someone else to be able to assist in future for this type of thing

**Pull request merged**
